
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_php_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: MilesChou/composer-action/7.4/install@master
        with:
          args: install --ignore-platform-reqs

      - uses: MilesChou/composer-action/7.4/install@master
        with:
          args: dump-autoload

      - name: Start containers
        working-directory: ./test_suite
        run: docker-compose up -d
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - run: php vendor/phpunit/phpunit/phpunit ./tests

