
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_php_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: MilesChou/composer-action/7.3/install@master
        with:
          args: install

      - uses: php-actions/phpunit@v3
        with:
          php_version: 7.3
          version: 9.3


